### ISSUE TITLE
Code coverage ownership

### ISSUE THREAD

**Issue by razvanphp** [JulienBreux/phpunit-docker#13]
Currently the generated code coverage and buid log are owned by root on the host.

Is there any way we can get this configurable with ENV variables [like this](https://github.com/docker/docker/issues/7198#issuecomment-112015480), until docker provides this functionality natively?

**Comment by JulienBreux** [comment]
I look for that ASAP ;)

**Comment by JulienBreux** [comment]
@razvanphp my #16 PR is ok for you?

**Comment by razvanphp** [comment]
I did use another solution in my case, so I can't really test, but looks good, thank you!

**Comment by JulienBreux** [comment]
Great, thx for your feedback ;)
