### ISSUE TITLE
Install pcntl extension

### ISSUE THREAD

**Issue by jmkgreen** [JulienBreux/phpunit-docker#14]
I am looking at a project that fails to test because composer cannot install https://github.com/sebastianbergmann/php-invoker/ ...

`phpunit/php-invoker 1.1.4 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.`

Add to the Dockerfile:

`RUN docker-php-ext-install pcntl`

Should fix it.

**Comment by jmkgreen** [comment]
In case of curiosity, Zend Framework 1 gets mentioned in the stack trace that led me to the above.

**Comment by JulienBreux** [comment]
Hi!
I fix it asap!
Thx

**Comment by JulienBreux** [comment]
Done! Sorry for time inconvenient.
