### ISSUE TITLE
Add support for php7

### ISSUE THREAD

**Issue by agiuliano** [JulienBreux/phpunit-docker#21]
The container run on top of php 5.6.
Php7 is going to be released, it could be very useful to have phpunit on top of php7.

**Comment by agiuliano** [comment]
In composer/composer they add a branch for php7, this PR (#22 ) make it possible to run on composer/composer:php7
Maybe should be merged into a php7 branch

**Comment by JulienBreux** [comment]
@agiuliano Great! I prepare a new master!
