### ISSUE TITLE
phpunit/phpunit:latest install php 5.6.15

### ISSUE THREAD

**Issue by agiuliano** [JulienBreux/phpunit-docker#25]
Even though the latest tag comes with phpunit 5.1.2, it comes also with php 5.6.15 and not php 7.0

**Comment by JulienBreux** [comment]
Thx for report :) I look that!

**Comment by chippyash** [comment]
yep - can confirm it.  You are using composer/composer:php7 as your base but the installed version of php if you exec into the container and do `php -v` the php is 5.6.x.  Maybe an upstream container problem.

**Comment by chippyash** [comment]
so. according to https://hub.docker.com/r/composer/composer there is no php7 variant tag

**Comment by JulienBreux** [comment]
Yeap, I think that I must separate my image from composer/composer :/

**Comment by chippyash** [comment]
Have fun with that Julien.  Perhaps you can respond to this thread when you get it sorted so all those watching get an update.  Happy to help test it out.  Good work chap.

**Comment by JulienBreux** [comment]
@chippyash thx! I work on it soon!

**Comment by andrewmclagan** [comment]
Yes +1 needing 7.x.x test coverage

**Comment by andrewmclagan** [comment]
check out the issue opened on composer docker file:

https://github.com/RobLoach/docker-composer/issues/78#issuecomment-221757183
