### ISSUE TITLE
Best practice installing extra modules

### ISSUE THREAD

**Issue by fatganz** [JulienBreux/phpunit-docker#38]
Is there any way to have extra modules installed in this image. E.g. my tests require bcmath module.
How I normally should handle this case? Custom image?

**Comment by up9cloud** [comment]
is it possible pre install all the pdo_mysql, pdo_pgsql, ...etc pdo drivers for database testing?

[phpunit offcial database testing intro](https://phpunit.de/manual/current/en/database.html)

```
Supported Vendors for Database Testing
DbUnit currently supports MySQL, PostgreSQL, Oracle and SQLite. Through Zend Framework or Doctrine 2 integrations it has access to other database systems such as IBM DB2 or Microsoft SQL Server.
```

**Comment by JulienBreux** [comment]
@fatganz, @up9cloud I change the based image for two reasons:
1. lighter image
2. flexible image

**Comment by JulienBreux** [comment]
@fatganz in the new image (avail. soon), the `bcmath` was enabled.
@up9cloud in the new image (avail. soon), the `pdo_*` was enabled.

**Comment by JulienBreux** [comment]
See #39.

**Comment by fatganz** [comment]
@JulienBreux thanks for your time and great job man!
