### ISSUE TITLE
Enable extensions installation from PECL

### ISSUE THREAD

**Issue by jbenoit2011** [JulienBreux/phpunit-docker#42]
I tried to build an image from this one where I installed a PHP extension through PECL.
But it failed because PHP is not built with XML in its core. And since PECL runs on top of PHP without any extensions, it gives errors. [more information](http://serverfault.com/a/612038).

Given PECL works great from DockerHub's official PHP Alpine image, I wonder if it would be possible to replace base image (alpine:edge) with DockerHub PHP Alpine image ?

It would improve phpunit image extensibility (by providing ability to install PECL) and make its Dockerfile much cleaner.

**Comment by JulienBreux** [comment]
Hi @jbenoit2011, 

I work hard to change the base image for you!

**Comment by JulienBreux** [comment]
Ok, I found a solution. (#44)

```
FROM phpunit/phpunit
MAINTAINER Julien BENOIT <julien.benoit@gmail.com>
ENV PEAR_PACKAGES foo bar baz
```

#smart

**Comment by JulienBreux** [comment]
@jbenoit2011 okey, build in progress :)

**Comment by JulienBreux** [comment]
@jbenoit2011 that's ok for you?

**Comment by jbenoit2011** [comment]
Actually, before I open this issue I workaround the problem by inheriting from another image. But I thought it would be valuable for other people to be aware of this problem.
I saw you include PEAR in the image.
On my side, I am trying, when I have 5 minutes, to include PECL as well.
I will let you know, through a PR, when it will be done.

**Comment by JulienBreux** [comment]
Nice, hoping you have helped 😃
