### ISSUE TITLE
tag 5.5.0 doesn't exist on Docker Hub

### ISSUE THREAD

**Issue by takamichi** [JulienBreux/phpunit-docker#45]
```sh
$ docker pull phpunit/phpunit:5.5.0
Pulling repository docker.io/phpunit/phpunit
Tag 5.5.0 not found in repository docker.io/phpunit/phpunit
```

**Comment by JulienBreux** [comment]
@takamichi Sorry for forgetting, it's in progress now.

<img width="751" alt="screen shot 2016-08-24 at 08 48 28" src="https://cloud.githubusercontent.com/assets/964330/17920921/8ba5b39c-69d7-11e6-8ee4-31c34a38c0ca.png">

**Comment by JulienBreux** [comment]
@takamichi is done for me :)

<img width="751" alt="screen shot 2016-08-24 at 08 55 34" src="https://cloud.githubusercontent.com/assets/964330/17921102/9237674a-69d8-11e6-86e0-58501bc9daf7.png">

**Comment by takamichi** [comment]
Thanks! 😄
