### ISSUE TITLE
ctype support.

### ISSUE THREAD

**Issue by rquadling** [JulienBreux/phpunit-docker#49]
Trying to find a version that contains ctype support and is PHP7

And is published to Docker.

Which one do I need to use?

**Comment by rquadling** [comment]
Seems I can use 5.4.2 (PHP 7.0.7 / PHPUnit 5.4.8 / Xdebug v2.4.0).

It would be REALLY nice to have the same extensions (where applicable) in all combinations.

It seems that after 5.4.2, ctype is not included, but, according to http://php.net/manual/en/ctype.installation.php, it suggests that this is an extension that SHOULD always be present. But with the user note regarding that an install is required for FreeBSD, maybe other platforms also require an installation.

**Comment by JulienBreux** [comment]
Hum, sorry, I don't understand.

What's your use case?

😃

**Comment by rquadling** [comment]
Basically, you are building PHP without the ctype extension.

As such, code which relies on ctype_xxx() functions cannot run due to a missing extension.

**Comment by rquadling** [comment]
After version 5.4.2 of your build process, you stopped using a predefined PHP process and built PHP manually. Without ctype.

**Comment by rquadling** [comment]
And so, only PHP 7.0.4 is testable for us, and not later versions of PHP.

**Comment by rquadling** [comment]
If you run `php -m` you will see the lack of ctype.

**Comment by JulienBreux** [comment]
In fact, now, `ctype` is available on new build method.

<img width="547" alt="screen shot 2016-12-30 at 15 57 41" src="https://cloud.githubusercontent.com/assets/964330/21566980/c0f2dcd8-cea8-11e6-978b-87cbeaafab84.png">

But you can used this image with an old version of PHP ?

**Comment by JulienBreux** [comment]
Hey @rquadling, I found the cause of the problem.

I fix'it now! 😄

**Comment by JulienBreux** [comment]
@rquadling this change is ok for you?

https://github.com/JulienBreux/phpunit-docker/pull/53/commits/fdae87d800776718ff3e0f9e1f793336c79cf380

**Comment by rquadling** [comment]
That looks good. I can't check this until I get back to our office on the 3rd. We are using the new Pipeline facility on Bitbucket so need to tell the rest of the team that I'm changing things for a bit.

**Comment by rquadling** [comment]
I want the latest versions of PHP (7.0.14), PHPUnit (5.7.0) and XDebug (2.5.0).

**Comment by JulienBreux** [comment]
Okey, let's go, build in progress :)

**Comment by rquadling** [comment]
Thank you.
