### ISSUE TITLE
No xdebug installed after v5.4.2

### ISSUE THREAD

**Issue by viktorsteinwand** [JulienBreux/phpunit-docker#50]
It seems that after the version v5.4.2 no xdebug is available due to following error message if execute phpunit:

```
phpunit -c phpunit.xml
PHPUnit 5.7.4 by Sebastian Bergmann and contributors.
Error:         No code coverage driver is available
...........................................                       43 / 43 (100%)
Time: 76 ms, Memory: 8.00MB
OK (43 tests, 68 assertions)
```

If using the version v5.4.2 the code coverage driver is available:

```
phpunit -c phpunit.xml.dist
PHPUnit 5.7.4 by Sebastian Bergmann and contributors.
...........................................                       43 / 43 (100%)
Time: 616 ms, Memory: 12.00MB
OK (43 tests, 68 assertions)
Generating code coverage report in Clover XML format ... done
Generating code coverage report in HTML format ... done
```

**Comment by JulienBreux** [comment]
In the phpunit-docker image ?

Because with the image, the message is : 
`PHPUnit 5.5.7 by Sebastian Bergmann, Julien Breux (Docker) and contributors.`

**Comment by viktorsteinwand** [comment]
The meaning of version number relates to the docker image, not to the phpunit itself:

`image: phpunit/phpunit:5.4.2` - works properly
`image: phpunit/phpunit:5.4.3` or `image: phpunit/phpunit:latest` - the code coverage driver do not work properly (xdebug is the code coverage driver)

**Comment by JulienBreux** [comment]
Thanks @viktorsteinwand,

And with de new `phpunit/phpunit:5.7.5` or the new `phpunit/phpunit:latest` ?

I will add more tests for coverage.

**Comment by JulienBreux** [comment]
Hey @viktorsteinwand, I found the cause of the problem.

I fix'it now! 😄
