### ISSUE TITLE
Missing PHP extension EXIF

### ISSUE THREAD

**Issue by emados** [JulienBreux/phpunit-docker#59]
I am getting the following error when running `composer install` and it seems that one of the packages requires the `ext-exif` extension. At first I thought I might need to `apt-get install` the extension but reading the PHP docs states that EXIF comes compiled with PHP and doesn't require any libraries/extensions.

There doesn't seem to be much information about how to address this issue out there, so I was hoping I could get some hints about what's going on, and whether this is an issue that needs to be fixed by the image.

**Used image:** phpunit/phpunit:5.0.3
**Error message:**

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for eventviva/php-image-resize 1.5.5 -> satisfiable by eventviva/php-image-resize[1.5.5].
    - eventviva/php-image-resize 1.5.5 requires ext-exif * -> the requested PHP extension exif is missing from your system.
```

**Comment by JulienBreux** [comment]
Hi @emados,

I just update image ASAP.

**Comment by JulienBreux** [comment]
(in progress)

**Comment by emados** [comment]
Oh! So the solution was to just really install the EXIF extension. Anyway, this issue is going to be updated after pushing the updated images to Docker Hub, right?

Thanks @JulienBreux for including this into the image and for your fast respond. 👍

**Comment by JulienBreux** [comment]
@emados it's good for you?

**Comment by emados** [comment]
Yup, the composer no installs with no errors. Thanks again @JulienBreux.

**Comment by JulienBreux** [comment]
@emados My pleasure ;)
