### ISSUE TITLE
PHPUnit Logo

### ISSUE THREAD

**Issue by sebastianbergmann** [JulienBreux/phpunit-docker#6]
Please do not use the old PHPUnit logo (https://secure.gravatar.com/avatar/a2c7222d3520d0ceb255bcbcbc82884c.jpg?s=200&d=mm) on https://registry.hub.docker.com/repos/phpunit/.

**Comment by JulienBreux** [comment]
Hi @sebastianbergmann,

No prob, but where is the new logo ?

**Comment by sebastianbergmann** [comment]
PHPUnit does not have a logo.

**Comment by JulienBreux** [comment]
Ok @sebastianbergmann, I removed the old logo.

(Just wait the Gravatar cache time)

Sorry for the inconvenience :/
