### ISSUE TITLE
Use a stable version of Alpine Linux

### ISSUE THREAD

**Issue by westy92** [JulienBreux/phpunit-docker#61]
The current version of Alpine Linux that is being used is the edge branch, which is unstable.

https://github.com/JulienBreux/phpunit-docker/blob/master/6.0.6/Dockerfile#L2

I think the switch to a stable branch is quite simple, `FROM alpine:latest`.

**Comment by JulienBreux** [comment]
@westy92 Nice idea, do you have a PR?

**Comment by westy92** [comment]
I do now! https://github.com/JulienBreux/phpunit-docker/pull/62
