### ISSUE TITLE
Building image for 6.0.6 fails: /usr/bin/php already exists

### ISSUE THREAD

**Issue by rousku** [JulienBreux/phpunit-docker#63]
Latest alpine image installs /usr/bin/php symlink and so building the docker image for 6.0.6 fails with following message: 

```
Executing busybox-1.26.2-r4.trigger
Executing ca-certificates-20161130-r2.trigger
OK: 48 MiB in 59 packages
ln: /usr/bin/php: File exists
```
Removing the line "&& ln -s /usr/bin/php7 /usr/bin/php \" fixes the issue.

**Comment by JulienBreux** [comment]
Hello @rousku a PR ? :)
