### ISSUE TITLE
Missed php module ext-xmlwriter

### ISSUE THREAD

**Issue by igortregub** [JulienBreux/phpunit-docker#66]
Hi, 
I tried to use phpunit/phpunit:5.7.5 
During running command **composer install** happened following error:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for phpunit/php-code-coverage 4.0.8 -> satisfiable by phpunit/php-code-coverage[4.0.8].
    - phpunit/php-code-coverage 4.0.8 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.
  Problem 2
    - phpunit/php-code-coverage 4.0.8 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.
    - phpunit/phpunit 5.5.7 requires phpunit/php-code-coverage ^4.0.1 -> satisfiable by phpunit/php-code-coverage[4.0.8].
    - Installation request for phpunit/phpunit 5.5.7 -> satisfiable by phpunit/phpunit[5.5.7].
  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php7/php.ini
    - /etc/php7/conf.d/00_bcmath.ini
    - /etc/php7/conf.d/00_ctype.ini
    - /etc/php7/conf.d/00_curl.ini
    - /etc/php7/conf.d/00_dom.ini
    - /etc/php7/conf.d/00_json.ini
    - /etc/php7/conf.d/00_mbstring.ini
    - /etc/php7/conf.d/00_mcrypt.ini
    - /etc/php7/conf.d/00_opcache.ini
    - /etc/php7/conf.d/00_openssl.ini
    - /etc/php7/conf.d/00_pcntl.ini
    - /etc/php7/conf.d/00_pdo.ini
    - /etc/php7/conf.d/00_session.ini
    - /etc/php7/conf.d/00_soap.ini
    - /etc/php7/conf.d/00_tokenizer.ini
    - /etc/php7/conf.d/00_xml.ini
    - /etc/php7/conf.d/00_zip.ini
    - /etc/php7/conf.d/00_zlib.ini
    - /etc/php7/conf.d/01_exif.ini
    - /etc/php7/conf.d/01_mysqlnd.ini
    - /etc/php7/conf.d/01_pdo_pgsql.ini
    - /etc/php7/conf.d/01_pdo_sqlite.ini
    - /etc/php7/conf.d/01_phar.ini
    - /etc/php7/conf.d/01_xmlreader.ini
    - /etc/php7/conf.d/02_pdo_mysql.ini
    - /etc/php7/conf.d/xdebug.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

I think this error was happened by missed php extension ext-xmlwriter which requires in the **phpunit/php-code-coverage** package for version 4.0.4 and higher.

**Comment by leeahoward** [comment]
having the same error.  no update on this?

**Comment by rousku** [comment]
Update your alpine:latest image by running `docker pull alpine:latest`

**Comment by igortregub** [comment]
It doesn't work:

Igors-Mac-mini-2:fb-comments-hider igortregub$ docker pull alpine:latest
latest: Pulling from library/alpine
Digest: sha256:1072e499f3f655a032e88542330cf75b02e7bdf673278f701d7ba61629ee3ebe
Status: Image is up to date for alpine:latest
Igors-Mac-mini-2:fb-comments-hider igortregub$ docker run -v $(pwd):/app -it --entrypoint /bin/bash phpunit/phpunit:5.7.5 
bash-4.3# cd www/ && composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/php-code-coverage 4.0.8 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.
    - phpunit/php-code-coverage 4.0.8 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.
    - Installation request for phpunit/php-code-coverage 4.0.8 -> satisfiable by phpunit/php-code-coverage[4.0.8].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php7/php.ini
    - /etc/php7/conf.d/00_bcmath.ini
    - /etc/php7/conf.d/00_ctype.ini
    - /etc/php7/conf.d/00_curl.ini
    - /etc/php7/conf.d/00_dom.ini
    - /etc/php7/conf.d/00_json.ini
    - /etc/php7/conf.d/00_mbstring.ini
    - /etc/php7/conf.d/00_mcrypt.ini
    - /etc/php7/conf.d/00_opcache.ini
    - /etc/php7/conf.d/00_openssl.ini
    - /etc/php7/conf.d/00_pcntl.ini
    - /etc/php7/conf.d/00_pdo.ini
    - /etc/php7/conf.d/00_session.ini
    - /etc/php7/conf.d/00_soap.ini
    - /etc/php7/conf.d/00_tokenizer.ini
    - /etc/php7/conf.d/00_xml.ini
    - /etc/php7/conf.d/00_zip.ini
    - /etc/php7/conf.d/00_zlib.ini
    - /etc/php7/conf.d/01_exif.ini
    - /etc/php7/conf.d/01_mysqlnd.ini
    - /etc/php7/conf.d/01_pdo_pgsql.ini
    - /etc/php7/conf.d/01_pdo_sqlite.ini
    - /etc/php7/conf.d/01_phar.ini
    - /etc/php7/conf.d/01_xmlreader.ini
    - /etc/php7/conf.d/02_pdo_mysql.ini
    - /etc/php7/conf.d/xdebug.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
bash-4.3#
