### ISSUE TITLE
Missing ext-simplexml and ext-fileinfo

### ISSUE THREAD

**Issue by smcjones** [JulienBreux/phpunit-docker#71]
Both assertions in this test fail:

    $this->assertTrue(function_exists('simplexml_load_file'));
    $this->assertTrue(function_exists('mime_content_type'));

When I add ext-simplexml and ext-fileinfo and re-compile, it succeeds.

Similarly, would be nice to have ext-mysqli installed but I can just add that in a custom build.

**Comment by JulienBreux** [comment]
Hi @smcjones,

You can open a PR to add this missing exts ;)

BR

**Comment by smcjones** [comment]
Sure thing!

**Comment by JulienBreux** [comment]
Thx for contribution.
